name: Auto Sync Fork

on:
  schedule:
    - cron: '*/5 * * * *'   # every 5 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Configure Git
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions@github.com"

      - name: Fetch & merge upstream
        run: |
          git remote add upstream https://github.com/kskoushik26/krsguesthouse.git || true
          git fetch upstream
          git checkout main
          git merge upstream/main --ff-only

      - name: Push
        run: git push origin main